name: Close Pull Request Public

on:
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  sync-repos-public:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Send API request to sync-repos-public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          my_string="${{ github.event.pull_request.title }}"
          pr_number=${my_string#*refs/pull/}  # remove everything before "refs/pull/"
          pr_number=${pr_number%%/*}  # remove everything after the first "/"
          echo $pr_number
          curl --request POST \
            --url https://api.github.com/repos/FChikh/sync_repos_public/issues/$pr_number/comments \
            --header "Authorization: Bearer ${{ secrets.PUBLIC_REPO_TOKEN }}" \
            --header 'Content-Type: application/json' \
            --data '{"body": "Your pull request has been declined."}'
          curl --request PATCH \
            --url https://api.github.com/repos/FChikh/sync_repos_public/pulls/$pr_number \
            --header "Authorization: Bearer ${{ secrets.PUBLIC_REPO_TOKEN }}" \
            --header 'Content-Type: application/json' \
            --data '{"state": "closed"}'
